nginx-extras: bump to 1.14.2

diff --git a/nginx-extras/src/modules/http-fancyindex/t/preamble b/nginx-extras/src/modules/http-fancyindex/t/preamble
--- a/nginx-extras/src/modules/http-fancyindex/t/preamble
+++ b/nginx-extras/src/modules/http-fancyindex/t/preamble
@@ -39,6 +39,22 @@ readonly NGINX_PID="${PREFIX}/logs/nginx.pid"
 rm -f "${NGINX_CONF}" "${NGINX_PID}"
 mkdir -p "${PREFIX}/logs"
 
+function pup () {
+	if [[ -x ${TESTDIR}/pup ]] ; then
+		"${TESTDIR}/pup" "$@"
+	else
+		skip 'Test uses "pup", which is not available'
+	fi
+}
+
+function use () {
+	case $1 in
+		pup ) [[ -x ${TESTDIR}/pup ]] \
+			|| skip 'Test uses "pup", which is unavailable\n' ;;
+		* ) warn "Invalid 'use' flag: '%s'\n'" "$1" ;;
+	esac
+}
+
 function nginx () {
 	env - PATH="${PATH}" "${PREFIX}/sbin/nginx" "$@"
 }
@@ -72,13 +88,19 @@ function fetch () {
 	wget "${opts[@]}" -O- "http://localhost:8888${1:-/}" 2>&1
 }
 
+function skip () {
+	printf '(--) '
+	printf "$@"
+	exit 111
+} 1>&2
+
 function fail () {
-	printf "(FF) "
+	printf '(FF) '
 	printf "$@"
 	exit 1
 } 1>&2
 
 function warn () {
-	printf "(WW)"
+	printf '(WW) '
 	printf "$@"
 } 1>&2
